import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useAppSelector } from "../../store";
import { safeInfoState } from "../../store/safeInfoSlice";

const Home: NextPage = () => {
  const router = useRouter();
  const { safeAddress } = router.query;

  const { address } = useAppSelector(safeInfoState);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Hello Balances of {safeAddress}</main>
      <pre>{JSON.stringify(address, null, 2)}</pre>
    </div>
  );
};

export default Home;
