import Head from 'next/head'
import type { NextPage } from 'next'

import { selectSafeInfo } from 'store/safeInfoSlice'
import SafeHeader from 'components/common/SafeHeader'
import useSafeAddress from 'services/useSafeAddress'
import { useAppSelector } from 'store'
import { selectChainById } from 'store/chainsSlice'
import useAssets from 'services/useAssets'

const Balances: NextPage = () => {
  const { chainId } = useSafeAddress()
  const safeInfo = useAppSelector(selectSafeInfo)
  const chainConfig = useAppSelector((state) => selectChainById(state, chainId))
  const { balances, loading } = useAssets()

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SafeHeader />

      <main>
        <h1>Hello Safe on {chainConfig?.chainName}</h1>
        Owners: {safeInfo.owners.map((item) => item.value).join(', ')}
        <h2>Balances {loading ? '(loading...)' : ''}</h2>
        {balances ? <pre>{JSON.stringify(balances, null, 2)}</pre> : null}
      </main>
    </div>
  )
}

export default Balances
