export const proxyAddress = '0xDfca3a8d7699D8bAfe656823AD60C17cb8270ECC'
export const ABI = [
  {
    type: 'constructor',
    stateMutability: 'nonpayable',
    payable: false,
    inputs: [{ type: 'bool', name: 'test', internalType: 'bool' }],
  },
  {
    type: 'event',
    name: 'AdjustmentSpeedSet',
    inputs: [{ type: 'uint256', name: 'adjustmentSpeed', internalType: 'uint256', indexed: false }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'GasPriceMinimumFloorSet',
    inputs: [{ type: 'uint256', name: 'gasPriceMinimumFloor', internalType: 'uint256', indexed: false }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'GasPriceMinimumUpdated',
    inputs: [{ type: 'uint256', name: 'gasPriceMinimum', internalType: 'uint256', indexed: false }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      { type: 'address', name: 'previousOwner', internalType: 'address', indexed: true },
      { type: 'address', name: 'newOwner', internalType: 'address', indexed: true },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RegistrySet',
    inputs: [{ type: 'address', name: 'registryAddress', internalType: 'address', indexed: true }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TargetDensitySet',
    inputs: [{ type: 'uint256', name: 'targetDensity', internalType: 'uint256', indexed: false }],
    anonymous: false,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'uint256', name: 'value', internalType: 'uint256' }],
    name: 'adjustmentSpeed',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'gasPriceMinimum',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'gasPriceMinimumFloor',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'getGasPriceMinimum',
    inputs: [{ type: 'address', name: 'tokenAddress', internalType: 'address' }],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'getUpdatedGasPriceMinimum',
    inputs: [
      { type: 'uint256', name: 'blockGasTotal', internalType: 'uint256' },
      { type: 'uint256', name: 'blockGasLimit', internalType: 'uint256' },
    ],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'pure',
    payable: false,
    outputs: [
      { type: 'uint256', name: '', internalType: 'uint256' },
      { type: 'uint256', name: '', internalType: 'uint256' },
      { type: 'uint256', name: '', internalType: 'uint256' },
      { type: 'uint256', name: '', internalType: 'uint256' },
    ],
    name: 'getVersionNumber',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'initialize',
    inputs: [
      { type: 'address', name: '_registryAddress', internalType: 'address' },
      { type: 'uint256', name: '_gasPriceMinimumFloor', internalType: 'uint256' },
      { type: 'uint256', name: '_targetDensity', internalType: 'uint256' },
      { type: 'uint256', name: '_adjustmentSpeed', internalType: 'uint256' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'initialized',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'isOwner',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'address', name: '', internalType: 'address' }],
    name: 'owner',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'address', name: '', internalType: 'contract IRegistry' }],
    name: 'registry',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'renounceOwnership',
    inputs: [],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'setAdjustmentSpeed',
    inputs: [{ type: 'uint256', name: '_adjustmentSpeed', internalType: 'uint256' }],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'setGasPriceMinimumFloor',
    inputs: [{ type: 'uint256', name: '_gasPriceMinimumFloor', internalType: 'uint256' }],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'setRegistry',
    inputs: [{ type: 'address', name: 'registryAddress', internalType: 'address' }],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'setTargetDensity',
    inputs: [{ type: 'uint256', name: '_targetDensity', internalType: 'uint256' }],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'uint256', name: 'value', internalType: 'uint256' }],
    name: 'targetDensity',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'transferOwnership',
    inputs: [{ type: 'address', name: 'newOwner', internalType: 'address' }],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'updateGasPriceMinimum',
    inputs: [
      { type: 'uint256', name: 'blockGasTotal', internalType: 'uint256' },
      { type: 'uint256', name: 'blockGasLimit', internalType: 'uint256' },
    ],
    constant: false,
  },
]
