/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface Create_callInterface extends utils.Interface {
  functions: {
    "performCreate(uint256,bytes)": FunctionFragment;
    "performCreate2(uint256,bytes,bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "performCreate",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "performCreate2",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "performCreate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "performCreate2",
    data: BytesLike
  ): Result;

  events: {
    "ContractCreation(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ContractCreation"): EventFragment;
}

export type ContractCreationEvent = TypedEvent<
  [string],
  { newContract: string }
>;

export type ContractCreationEventFilter =
  TypedEventFilter<ContractCreationEvent>;

export interface Create_call extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: Create_callInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    performCreate(
      value: BigNumberish,
      deploymentData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    performCreate2(
      value: BigNumberish,
      deploymentData: BytesLike,
      salt: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  performCreate(
    value: BigNumberish,
    deploymentData: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  performCreate2(
    value: BigNumberish,
    deploymentData: BytesLike,
    salt: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    performCreate(
      value: BigNumberish,
      deploymentData: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    performCreate2(
      value: BigNumberish,
      deploymentData: BytesLike,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "ContractCreation(address)"(
      newContract?: null
    ): ContractCreationEventFilter;
    ContractCreation(newContract?: null): ContractCreationEventFilter;
  };

  estimateGas: {
    performCreate(
      value: BigNumberish,
      deploymentData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    performCreate2(
      value: BigNumberish,
      deploymentData: BytesLike,
      salt: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    performCreate(
      value: BigNumberish,
      deploymentData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    performCreate2(
      value: BigNumberish,
      deploymentData: BytesLike,
      salt: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
