import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";

import { useAppDispatch } from "store";
import { getChains } from "store/chainsSlice";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const dispatch = useAppDispatch();

  useEffect(() => {
    dispatch(getChains());
  }, [dispatch]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Hello web-core</main>
    </div>
  );
};

export default Home;
