import Head from "next/head";
import type {NextPage} from "next";

const History: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>History</main>
    </div>
  );
};

export default History;
