import Head from "next/head";
import type {NextPage} from "next";

const Queue: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Queue</main>
    </div>
  );
};

export default Queue;
